"""
Train a PINN to estimate the volatility (sigma) of the Black-Scholes equation.
Assumes a constant volatility.

Given a stored PDE solution, this script trains a ConstrainedFCN (see model.py)
network while simultaneously optimising the volatility parameter sigma.
The training alternates between updating the network weights and updating sigma,
in order to improve the stability of the convergence towards the true value of
sigma.

Command-line usage:
    python backwards.py -d <data_path> -s <save_path>

The data_path should point to an HDF5 file generated by data_gen.py
(or any other method, so long as the metadata matches,
see data_gen.py for more on that)
which contains the PDE solution to fit. The trained model is
saved to the specified path, and the true value of sigma
is printed in the terminal.
"""

import argparse

import matplotlib.pyplot as plt
import torch
from model import ConstrainedFCN

from common.classes import BlackScholesPDE, Domain
from common.funcs import modify_domain, read_black_scholes_run
from common.pinn_helpers import (
    create_left_boundary,
    create_right_boundary,
    gen_phys_training_pts,
    get_derivatives,
)
from pinn.pinn_io import save_pinn
from pinn.plot_heatmap import plot_single, predict_grid


def create_data_points(
    data: torch.Tensor,
    x_min: float,
    x_max: float,
    t_min: float,
    t_max: float,
    x_scale: float,
):
    """
    Build (x, t) input points and matching targets from a stored PDE run's
    solution tensor, in the same normalized [0, 1] x [0, 1] space used
    everywhere else in this module.

    Args:
        data: The solved PDE field values (forward-chronological).
        x_min: Spatial domain lower bound.
        x_max: Spatial domain upper bound.
        t_min: Temporal domain lower bound.
        t_max: Temporal domain upper bound.
        x_scale: The physical range of the spatial domain, used to normalize
            the PDE values to match the rest of the model's targets.

    Returns:
        data_inputs:
            Tensor with columns (x, t) representing the input points.
        u_real:
            Tensor containing the corresponding normalized target values.
    """
    n_times, n_x = data.shape
    x_data = torch.linspace(x_min, x_max, n_x)
    t_data = torch.linspace(t_min, t_max, n_times)
    # indexing="ij" with (t, x) so flattening matches data's (n_times, n_x)
    # row-major layout: t varies slowest, x varies fastest.
    space_t_data, space_x_data = torch.meshgrid(t_data, x_data, indexing="ij")

    data_inputs = torch.stack((space_x_data.flatten(), space_t_data.flatten()), dim=-1)
    u_real = (data.flatten() / x_scale).view(-1, 1)
    return data_inputs, u_real


# The following function(s) help set up training
def train(
    domain: Domain, params: BlackScholesPDE, data: torch.Tensor
) -> tuple[ConstrainedFCN, float, list[float]]:
    """
    Trains a PINN in order to calculate sigma.

    Args:
        domain:
            A ``Domain`` object which specifies the distribution of
            physics training points.
        params:
            A ``BlackScholesPDE`` object specifying observable
            parameters of the equation.
        data:
            a ``Tensor`` containing the data from which to estimate
            sigma.

    Returns:
        pinn:
            The trained network.
        sig_est_final:
            The final estimate of sigma.
        sig_history:
            A list containing all estimates for sigma
            throughout training.

    """
    torch.manual_seed(123)
    # PDE paramenters
    MIN_X = domain.mindim(0)
    MAX_X = domain.maxdim(0)
    NUM_PTS_X = domain.ndim(0)
    MIN_T = domain.t_min
    MAX_T = domain.t_max
    NUM_PTS_T = domain.nt

    # Unnormalized contract parameters.
    SIG = params.sigma
    R = params.r
    STRIKE = params.k

    # Normalize
    X_SCALE = MAX_X - MIN_X
    T_SCALE = MAX_T - MIN_T
    U_SCALE = MAX_X - MIN_X
    _ = U_SCALE

    STRIKE = (STRIKE - MIN_X) / X_SCALE
    SIG = SIG * (T_SCALE**0.5)
    R = R * T_SCALE
    MIN_X, MAX_X = 0.0, 1.0
    MIN_T, MAX_T = 0.0, 1.0

    # Setup
    t_boundary_x_limits = torch.linspace(MIN_T, MAX_T, NUM_PTS_T).requires_grad_(True)
    bdry_left, u_bdry_left_tgt = create_left_boundary(t_boundary_x_limits, MIN_X)
    bdry_right, u_bdry_right_tgt = create_right_boundary(
        t_boundary_x_limits, MAX_X, STRIKE=STRIKE, R=R, T_MAX=MAX_T, S_MAX=MAX_X
    )

    # Data points/targets straight from the stored PDE solve. This is the
    # actual solution the PDE solver computed, so fitting to it grounds the
    # PINN in real data rather than relying only on the IC/BC/physics terms.
    data_inputs, u_real = create_data_points(data, MIN_X, MAX_X, MIN_T, MAX_T, X_SCALE)

    t_phys, x_phys, phys_inputs = gen_phys_training_pts(
        MIN_T, MAX_T, MIN_X, MAX_X, NUM_PTS_T, NUM_PTS_X
    )

    print(f"Shape of physics_inputs (x,t): {phys_inputs.shape}")
    print(f"Shape of data_inputs (x,t): {data_inputs.shape}")

    # PINN setup
    KINK_WIDTH = 0.05
    pinn = ConstrainedFCN(
        input_dim=2,
        output_dim=1,
        hidden_dim=64,
        num_layers=3,
        strike=STRIKE,
        t_max=MAX_T,
        kink_width=KINK_WIDTH,
    )

    # Initial guess for sigma
    sig_init = 0.05
    sig_init_scaled = sig_init * (T_SCALE**0.5)

    # Train against the logarithm of sigma, in order to improve
    log_sig_est = torch.nn.Parameter(
        torch.log(torch.tensor([sig_init_scaled])).view(-1, 1)
    )

    sig_history = []

    # Sigma & the network require different learning rates,
    # (and separate training cycles appear to produce better results),
    # so they have separate optimisers.
    optim_net = torch.optim.Adam(
        [
            {"params": pinn.parameters(), "lr": 5e-4},
        ]
    )
    # optim_sig = torch.optim.Adam([log_sig_est], 0.9, (0.55, 0.99))
    optim_sig = torch.optim.SGD([log_sig_est], 1, 0.8)

    # lambda2 (physics loss weight) is raised relative to lambda1/lambda3, as
    # the physics residual is smaller in scale than the data/boundary losses.
    lambda1, lambda2, lambda3 = 1, 5, 2

    # sigma_phase determines whether sigma or the PINN are being trained
    # during the training loop.
    sigma_phase = False

    def compute_loss():
        # Data loss: fit the PINN to the actual solved PDE run.
        u_data_pred = pinn(data_inputs)
        data_loss = torch.mean((u_data_pred - u_real) ** 2)

        # Boundary losses (left/right spatial boundaries).
        u_bdry_left_pred = pinn(bdry_left)
        boundary_left_loss = torch.mean((u_bdry_left_pred - u_bdry_left_tgt) ** 2)

        u_bdry_right_pred = pinn(bdry_right)
        boundary_right_loss = torch.mean((u_bdry_right_pred - u_bdry_right_tgt) ** 2)

        u_phys = pinn(phys_inputs)

        # derivatives w.r.t. t, x
        (dudt_phys,) = get_derivatives(u_phys, t_phys, 1)
        dudx_phys, d2udx2_phys = get_derivatives(u_phys, x_phys, 2)

        x_phys_view = x_phys.view(-1, 1)
        sig_est = torch.exp(log_sig_est)
        # Physics loss
        loss_phys = torch.mean(
            (
                dudt_phys
                + 1 / 2 * sig_est**2 * (x_phys_view**2) * d2udx2_phys
                + R * (x_phys_view) * dudx_phys
                - R * u_phys
            )
            ** 2
        )

        # backpropagate joint loss, take optimiser step
        loss = (
            lambda3 * data_loss
            + lambda1 * (boundary_left_loss + boundary_right_loss)
            + lambda2 * loss_phys
        )
        return loss, data_loss, boundary_left_loss, boundary_right_loss, loss_phys

    for i in range(200001):
        if not sigma_phase:
            optim_net.zero_grad()

        else:
            optim_sig.zero_grad()
        loss, loss1, loss2, loss3, loss4 = compute_loss()
        loss.backward(retain_graph=True)  # Added retain_graph=True here
        if not sigma_phase:
            optim_net.step()

        else:
            optim_sig.step()
            sig_history.append(torch.exp(log_sig_est).item())
        if i % 500 == 0:
            print(
                f"[Adam] {i}/16000. Loss: {loss.item():.6e}. "
                f"L1(data): {loss1.item():.6e}. L2(bdry_left): {loss2.item():.6e}. "
                f"L3(bdry_right): {loss3.item():.6e}. L4(phys): {loss4.item():.6e}. "
                f"sig: {torch.exp(log_sig_est).item():.6e}"
            )
        if i % 2000 == 1820:
            sigma_phase = True
            print("Switch phase to: 'Training sigma'")
            for param in pinn.parameters():
                param.requires_grad_(not sigma_phase)
            log_sig_est.requires_grad_(sigma_phase)
        if i % 2000 == 0:
            sigma_phase = False
            print("Switch phase to: 'Training network'")
            for param in pinn.parameters():
                param.requires_grad_(not sigma_phase)
            log_sig_est.requires_grad_(sigma_phase)

    loss, loss1, loss2, loss3, loss4 = compute_loss()
    sig_est_final = torch.exp(log_sig_est).item()
    sig_est_final_scaled = sig_est_final / T_SCALE
    print(
        f"[FINAL] Loss: {loss.item():.6e}. "
        f"L1(data): {loss1.item():.6e}. L2(bdry_left): {loss2.item():.6e}. "
        f"L3(bdry_right): {loss3.item():.6e}. L4(phys): {loss4.item():.6e}. "
    )
    print(
        f"[FINAL] est. sigma:{sig_est_final_scaled:.6e} true sigma:{params.sigma:.6e}"
    )
    return pinn, sig_est_final_scaled, sig_history


def main():
    """
    Executes the following tasks:
        1. Parse command-line arguments
        2. set up the domain and PDE parameters,
        3. PINN training
        4. Plot sigma evolution during training
        4. Save model to path given by ``--saveto``
        5. generate a heatmap plot of the PINN output
    """
    device = "cpu"
    if torch.cuda.is_available():
        device = "cuda"
        print("GPU available. Running on GPU.")
    torch.set_default_device(device)

    parser = argparse.ArgumentParser(description="Plot PINN solution heatmap.")
    parser.add_argument(
        "-d", "--data", type=str, required=True, help="Path to training data"
    )
    parser.add_argument(
        "-s",
        "--saveto",
        type=str,
        default="models/pinn_backward_new.pt",
        help="Path to where the model should be saved",
    )
    args = parser.parse_args()

    # Load the domain/PDE params this run was solved with, plus the actual
    # solved field values as a tensor to train against.
    domain, params, data = read_black_scholes_run(
        args.data, spatial_resolution=20, time_steps=20
    )
    domain = modify_domain(domain, resolution=(100,), _t_res=50)
    pinn, sig_est_final, sig_hist = train(domain, params, data)
    plt.figure(figsize=(8, 5))
    plt.plot(sig_hist, linewidth=2)
    plt.xlabel("Epochs")
    plt.ylabel("Estimated sigma")
    plt.title("Sigma evolution during training")
    plt.grid(True)
    plt.savefig("sig_loss_hist_new_rate_low.png", dpi=150)
    plt.close()

    save_pinn(
        args.saveto,
        pinn,
        pinn.metadata,
        domain=domain.to_metadata(),
        pde=params.to_metadata(),
        extra={"sig_est": sig_est_final},
    )
    pinn = pinn.to("cpu")
    torch.set_default_device("cpu")
    x, t, pred = predict_grid(
        pinn,
        domain.mindim(0),
        domain.maxdim(0),
        domain.t_min,
        domain.t_max,
        domain.ndim(0),
        domain.nt,
        device,
        rescale=True,
    )
    plot_single(x, t, pred, "PINN output", "figs/pinn_results.png")


if __name__ == "__main__":
    main()
